[versions]
androidx-activity = "1.9.2"
androidx-annotation = "1.8.2"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.13.1"
androidx-datastore = "1.1.1"
androidx-fragment = "1.8.2"
androidx-lifecycle = "2.8.4"
androidx-multidex = "2.0.1"
androidx-recyclerview = "1.3.2"
androidx-test-core = "1.6.1"
androidx-test-junit = "1.2.1"
androidx-test-runner = "1.6.2"
app-review = "2.0.1"
arcmutate-base = "1.3.1"
arcmutate-kotlin = "1.3.0"
barista = "4.3.0"
dependency-analysis = "2.0.1"
desugar = "2.1.2"
detekt = "1.23.6"
gradle = "8.6.0"
gradle-pitest = "1.15.0"
junit = "4.13.2"
koin = "3.5.6"
koin-annotations = "1.3.1"
konsist = "0.16.0"
korlibs = "6.0.0-alpha2"
kotest = "5.9.1"
kotest-koin = "1.3.0"
kotest-pitest = "1.2.0"
kotlin = "2.0.20"
kotlin-coroutines = "1.9.0-RC.2"
kotlin-datetime = "0.6.1"
kotlinpoet = "1.18.1"
kover = "0.8.3"
ksp = "2.0.20-1.0.24"
ktor = "2.3.12"
leakcanary = "2.14"
mockk = "1.13.12"
okio = "3.9.0"
pitest = "1.16.1"
pitest-junit5 = "1.2.1"
play-services-tasks = "18.2.0"
protobuf = "4.28.0"
protobuf-plugin = "0.9.4"
task-tree = "4.0.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-pitest = { module = "info.solidsoft.gradle.pitest:gradle-pitest-plugin", version.ref = "gradle-pitest" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }

koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-koin = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }

korlibs-charset = { module = "com.soywiz:korlibs-charset", version.ref = "korlibs" }
korlibs-xml = { module = "com.soywiz:korlibs-serialization-xml", version.ref = "korlibs" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-assets = { module = "com.squareup.okio:okio-assetfilesystem", version.ref = "okio" }

activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
core = { module = "androidx.core:core", version.ref = "androidx-core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

app-review = { module = "com.google.android.play:review", version.ref = "app-review" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "play-services-tasks" }

protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }

protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

barista = { module = "com.adevinta.android:barista", version.ref = "barista" }
junit = { module = "junit:junit", version.ref = "junit" }

kotest-assertions-api = { module = "io.kotest:kotest-assertions-api", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
kotest-common = { module = "io.kotest:kotest-common", version.ref = "kotest" }
kotest-extensions-koin = { module = "io.kotest.extensions:kotest-extensions-koin", version.ref = "kotest-koin" }
kotest-extensions-pitest = { module = "io.kotest.extensions:kotest-extensions-pitest", version.ref = "kotest-pitest" }
kotest-framework-api = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-framework-datatest-jvm = { module = "io.kotest:kotest-framework-datatest-jvm", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }

arcmutate-base = { module = "com.arcmutate:base", version.ref = "arcmutate-base" }
arcmutate-kotlin = { module = "com.arcmutate:pitest-kotlin-plugin", version.ref = "arcmutate-kotlin" }

konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }

accessibility-test-framework = { module = "com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework", version = "latest.release" }
bouncycastle = { module = "org.bouncycastle:bcpkix-jdk18on", version = "latest.release" }
commons-compress = { module = "org.apache.commons:commons-compress", version = "latest.release" }
guava = { module = "com.google.guava:guava", version = "latest.release" }
jsoup = { module = "org.jsoup:jsoup", version = "latest.release" }
netty = { module = "io.netty:netty-codec-http2", version = "4.1.+" }

[bundles]
classpath = [
    "gradle",
    "kotlin-gradle-plugin",
    "gradle-pitest",
]

app = [
    "kotlin-stdlib",
    "kotlinx-coroutines",
    "activity",
    "annotation",
    "appcompat",
    "constraintlayout",
    "core",
    "core-ktx",
    "datastore",
    "datastore-core",
    "fragment",
    "fragment-ktx",
    "lifecycle-common",
    "lifecycle-runtime",
    "lifecycle-service",
    "lifecycle-viewmodel",
    "multidex",
    "recyclerview",
    "okio",
    "okio-assets",
    "protobuf-javalite",
    "protobuf-kotlin-lite",
    "app-review",
    "play-services-tasks",
]
app-debug = [
    "leakcanary",
]
app-androidTest = [
    "barista",
    "junit",
    "test-core",
    "test-junit",
    "test-runner",
]

ian = [
    "kotlinx-coroutines",
    "kotlinx-datetime",
    "ktor-io",
    "ktor-network",
]
ian-test = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "mockk",
    "mockk-dsl",
]
ian-test-runtime = [
    "kotest-extensions-pitest",
    "kotest-runner-junit5-jvm",
]

ian-enums-test = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "mockk",
]

ian-listener-test = [
    "kotest-assertions-core",
    "kotest-framework-api",
    "mockk",
    "mockk-dsl",
]

ian-packets-api = [
    "kotlin-stdlib",
    "kotlinx-coroutines",
    "kotlinx-datetime",
    "koin-annotations",
    "koin-core",
    "korlibs-charset",
    "ktor-io",
]
ian-packets-test = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-extensions-koin",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "koin-test",
    "mockk",
    "mockk-dsl",
]
ian-packets-test-fixtures = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "mockk",
    "mockk-dsl",
]

ian-udp-api = [
    "kotlin-stdlib",
    "kotlinx-coroutines",
    "ktor-io",
    "ktor-network",
]
ian-udp-test = [
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "mockk",
    "mockk-dsl",
]

ian-util = [
    "kotlinx-coroutines",
    "korlibs-charset",
    "ktor-io",
    "okio",
]
ian-util-test = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-framework-engine",
    "kotest-property",
    "mockk",
]
ian-util-test-fixtures = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-engine",
    "kotest-property",
    "mockk",
]

ian-vesseldata = [
    "korlibs-xml",
    "okio",
]
ian-vesseldata-test = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-engine",
    "kotest-property",
    "mockk",
]
ian-vesseldata-test-fixtures = [
    "kotest-assertions-api",
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-engine",
    "kotest-property",
    "korlibs-xml",
    "mockk",
]

ian-world-test = [
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-common",
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "kotest-property",
    "mockk",
    "mockk-dsl",
]
ian-world-test-fixtures = [
    "kotest-assertions-core",
    "kotest-assertions-shared",
    "kotest-framework-api",
    "kotest-property",
    "mockk",
    "mockk-dsl",
]

konsist-common = [
    "kotest-framework-api",
    "kotest-framework-datatest-jvm",
    "konsist",
]
konsist-app = [
    "fragment",
    "kotest-assertions-core",
]
konsist-ian = [
    "kotest-assertions-core",
]
konsist-vesseldata = [
    "korlibs-xml",
]
konsist-runtime = [
    "kotest-runner-junit5-jvm",
]

arcmutate = [
    "arcmutate-base",
    "arcmutate-kotlin",
]

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }
